### ISSUE TITLE
Пользователь. Просмотр Личного кабинета

### ISSUE THREAD

**Issue by UralbekXD** [AttractorSchool/ESDP-AP-10-4#18]
## Для чего это нужно:
Для того чтобы пользователь мог просматривать личную информацию.

## Как это сделать:
Нужно написать View представление в приложении accounts,добавить все нужные шаблоны для отображения контента
**Должны отображаться следующая информация:**
- **ФИО**
- **email**
- **Номер телефона**
- **Город проживания**
- **Дата рождения**

## Критерий приема:
- Вся информация на странице отображается корректно

## Время выполнения:
- 1-2 часа

**Comment by romeeeoo** [comment]
- добавить забронированные туры

**Comment by UralbekXD** [comment]
Нужно сделать анализ запросов в шаблонах
И выбрать те которые встречаются чаще всего, чтобы потом
подготовить запросы в представлений
