### ISSUE TITLE
Бронирование тура

### ISSUE THREAD

**Issue by Russo2642** [AttractorSchool/ESDP-AP-10-4#23]
#23 Бронирование туров

## Для чего это нужно

Функционал сайта завязан на бронирование и покупке туров. В первую очередь необходимо реализовать функционал бронирования туров для взимания предоплаты за участие в туре

## Как это сделать

- Пользователю, после нажатия на кнопку "Забронировать тур", выходит модальное окно с уведомлением о том, что: `См. "уведомление в модальном окне"`
- После нажатия на кнопку "Забронировать тур", у пользователя списываются 3.000 тенге и меняется состояния тура
- Смена состояния тура: 

  1. Меняется количество человек, необходимых для проведения тур
  2. Тур становится активным при достаточном количестве людей
  3. При полном наборе людей на тур - тур закрывается
  4. Оставшаяся оплата за тур происходит за 10-12 часов до начала тура и списывается у пользователя

## Уведомление в модальном окне

- Оплата за бронирование тура составляет 3.000 тенге
- Полная сумма за тур является не точной и зависит от количества человек, принимающих участие в группе
- Окончательная стоимость за тур отобразится за сутки до начала тура
- Вы не сможете вернуть предоплату за сутки до начала тура
- Согласие клиента (оферта)

## Калькуляция цены: [calculation.csv](https://docs.google.com/spreadsheets/d/1as-slQeAD1PIj2wBa2xzhVEs8m6idRHf6Octbe6p2sQ/edit?usp=sharing) (для демонстрации калькуляций)

- Цена Тура не должна высвечиваться в карточках с информацией о туре (ЦЕНА ТУРА)
- Цену Тура пока оставить в **backend**
- Показывать только цену о дипозите (ДЕПОЗИТ С ТУРИСТА)

## Критерий приёма
 Пользователь нажимает на кнопку "Забронировать тур", после чего выходит модальное окно с соглашением пользователя и с кнопкой "Продолжить", после чего у пользователя списываются деньги и меняется состояние тура

**Comment by romeeeoo** [comment]
@AigerimAvezbaeva @Russo2642 @UralbekXD 
- Наставник уточнил пока создание происходит посоле без снятия суммы. @Russo2642 скоректируй этот пункт
- Модкалку тоже можно пока убрать, чтобы не возится с JS
