### ISSUE TITLE
Решить конфликт отображения и обновления профиля гида

### ISSUE THREAD

**Issue by UralbekXD** [AttractorSchool/ESDP-AP-10-4#51]
**Проблема:**
1. Если гид создал туры после того как админ поставил статус профиля CONFIRMED
а потом гид обновил свой профиль, _**то его профиль не отображается пользователям.**_

Возможное решение
- Пока у гида есть активные туры он не может обновлять свой профиль
- **Закрыть возможность отправки профиля на проверку в статусе CONFIRMED для гида**  (сейчас сделал так)
- Отображать все профили гидов в статусе кроме NOT VERIFIED

**Comment by romeeeoo** [comment]
@UralbekXD исправил и решил, глянь
